external_data_config:
  external_data_csv: data/external/train.csv

raw_data_config:
  raw_data_csv: data/raw/train.csv
  categorical_feature: ['site_id', 'site_domain', 'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
                         'device_ip', 'device_model']
  train_test_split_ratio: 0.2
  target: click
  random_state: 48
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_data_csv: data/processed/ctr_train.csv
  test_data_csv: data/processed/ctr_test.csv

mlflow_config:
  artifact_dir: artifacts
  experiment_name: model_iteration_1
  run_name: lightgbm
  registered_model_name: lightgbm_model
  remote_server_uri: http://localhost:1234

lightgbm:
  task: train
  boosting_type: gbdt
  objective: binary
  metric: binary_logloss
  num_leaves: 31
  learning_rate: 0.08
  feature_fraction: 0.7
  bagging_fraction: 0.3
  bagging_freq: 5
  verbose: 0

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: click
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html




#  params: {'task': 'train','boosting_type': 'gbdt','objective': 'binary','metric': { 'binary_logloss'},'num_leaves': 31,'learning_rate': 0.08,'feature_fraction': 0.7,'bagging_fraction': 0.3,'bagging_freq': 5,'verbose': 0}
