channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=21.3.1
- pip:
  - mlflow
  - cffi==1.15.1
  - defusedxml==0.7.1
  - lightgbm==3.3.2
  - matplotlib==3.5.2
  - pandas==1.4.3
  - psutil==5.9.1
  - typing-extensions==4.3.0
name: mlflow-env
